### ISSUE TITLE
Como rodar o www no meu localhost?

### ISSUE THREAD

**Issue by stephencamilo** [atados/www#49]
Pessoal como rodar o site no meu localhost???
Segui as instruções do README.md mas resultou em:
# Server not found

**Comment by leonardoarroyo** [comment]
Opa, o que aparece no teu terminal quando você dá o grunt serve?
Ele chega a iniciar o servidor?

Deveria aparecer o seguinte:
Running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858
Express server listening on port 9000 in development mode

**Comment by stephencamilo** [comment]
![screenshot from 2016-04-01 23-58-45](https://cloud.githubusercontent.com/assets/619543/14224080/bffe863e-f865-11e5-8500-4b26652f7775.png)

**Comment by stephencamilo** [comment]
![screenshot from 2016-04-02 00-00-47](https://cloud.githubusercontent.com/assets/619543/14224086/faceecae-f865-11e5-8e00-d9ea57e6ffb5.png)

**Comment by leonardoarroyo** [comment]
@stephencamilo você ainda precisa de ajuda com este problema?
